// <auto-generated />
namespace ismaildenzzz.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test101));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071128270_Test101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
